# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options
image_size: 1024
MultiDis: 5
batch_size: 5
style_train_debug: 2
mode_data: 'normal'     # Either normal with augmentation or faces without augmentation. 
Identity: True          # With identity loss
Deterministic: False    # Deterministic approach

save_epoch: 1
c_dim: 10               # Number of domains
lambda_mask: 1.0        # Lambda for attention loss

ALL_ATTR_1:
  c_dim: 40
  save_epoch: 1
  num_epochs: 300
  num_epochs_decay: 200
  MultiDis: 1
  lambda_idt: 15
  dataset: 'All_Attributes'